name: portfolio_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flip_card: ^0.7.0
  carousel_slider: ^4.2.1
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: DM Serif Text
      fonts:
        - asset: fonts/DMSerifText-Regular.ttf
        - asset: fonts/DMSerifText-Italic.ttf
          style: italic
    - family: DM Mono
      fonts:
        - asset: fonts/DMMono-Regular.ttf
        - asset: fonts/DMMono-Italic.ttf
          style: italic
        - asset: fonts/DMMono-Medium.ttf
          weight: 500

  assets:
    - assets/images/
    - assets/images/projects/
    - assets/projectsData.json
